import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmEstudiantes extends javax.swing.JFrame {
    Conexion c = new Conexion();
    EstudiantesDAO e = new EstudiantesDAO();
    Estudiantes est = new Estudiantes();
    
    
    
    String nombres;
    String apellidos;
    String fecha;
    String correo_ins;
    String correo_per;
    String programa;
    long num_fijo;
    long num_cel;
    
    
    
    public frmEstudiantes() {
        initComponents();
        c.abrirConexion();
        mostrarJTableEstudiantes();
    }
    
    
    public void mostrarJTableEstudiantes(){
        try {
            
            DefaultTableModel mod = new DefaultTableModel();
            jTableEstudiantes.setModel(mod);
            PreparedStatement pst = c.conexion.prepareStatement("Select * from Estudiantes");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            int cantColums = rsmd.getColumnCount();
            
            mod.addColumn("Nombres");
            mod.addColumn("Apellidos");
            mod.addColumn("Fecha de nacimiento");
            mod.addColumn("Correo Institucional");
            mod.addColumn("Correo Personal");
            mod.addColumn("Número Celular");
            mod.addColumn("Número Fijo");
            mod.addColumn("Programa");
            
            while(rs.next()){
                Object[] filas = new Object[cantColums];
                for (int i = 0; i < cantColums; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                mod.addRow(filas);
            }
            pst.close();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    
    
    public void buscarEstudiantes(String correo_ins){
        try {
            PreparedStatement pst = c.conexion.prepareStatement("Select * from Estudiantes where Correo_Institucional = ?");
            pst.setString(1, correo_ins);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                txtNombres.setText(rs.getString("Nombres"));
                txtApellidos.setText(rs.getString("Apellidos"));
                txtFecha.setText(rs.getString("Fecha_Nacimiento"));
                txtCorreo_ins.setText(rs.getString("Correo_Institucional"));
                txtCorreo_per.setText(rs.getString("Correo_Personal"));
                txtNum_cel.setText(rs.getString("Numero_Celular"));
                txtNum_fijo.setText(rs.getString("Numero_fijo"));
                txtPrograma.setText(rs.getString("Programa"));
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro ningun registro", "Registro de estudiantes", JOptionPane.ERROR_MESSAGE);
            }
            pst.close();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    
    
    public void limpiarDatos(){
        txtNombres.setText("");
        txtApellidos.setText("");
        txtFecha.setText("");
        txtCorreo_ins.setText("");
        txtCorreo_per.setText("");
        txtNum_cel.setText("");
        txtNum_fijo.setText("");
        txtPrograma.setText("");
        txtNombres.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtCorreo_ins = new javax.swing.JTextField();
        txtCorreo_per = new javax.swing.JTextField();
        txtNum_cel = new javax.swing.JTextField();
        txtNum_fijo = new javax.swing.JTextField();
        txtPrograma = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEstudiantes = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INSTITUTO LA FLORESTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel1.setText("Nombres:");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("Fecha de nacimiento:");

        jLabel4.setText("Correo Institucional:");

        jLabel5.setText("Correo Personal:");

        jLabel6.setText("Número de teléfono celular:");

        jLabel7.setText("Número de teléfono fijo:");

        jLabel8.setText("Programa académico:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNum_fijo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(txtNum_cel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo_per, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo_ins, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrograma))
                .addGap(208, 208, 208))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreo_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreo_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNum_cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNum_fijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jTableEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEstudiantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(27, 27, 27)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(32, 32, 32)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBorrar)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (!txtNombres.getText().isEmpty() && !txtApellidos.getText().isEmpty() && !txtFecha.getText().isEmpty() && !txtCorreo_ins.getText().isEmpty() && !txtCorreo_per.getText().isEmpty() && !txtNum_cel.getText().isEmpty() && !txtNum_fijo.getText().isEmpty() && !txtPrograma.getText().isEmpty()){
            correo_ins = txtCorreo_ins.getText();
            if (!e.verificarBD(correo_ins)) {
                nombres = txtNombres.getText();
                apellidos = txtApellidos.getText();
                fecha = txtFecha.getText();
                correo_ins = txtCorreo_ins.getText();
                correo_per = txtCorreo_per.getText();
                num_cel = Long.parseLong(txtNum_cel.getText());
                num_fijo = Long.parseLong(txtNum_fijo.getText());
                programa = txtPrograma.getText();
                e.insertarEstudiante(nombres, apellidos, fecha, correo_ins, correo_per, num_cel, num_fijo, programa);
                JOptionPane.showMessageDialog(null,"El registro fue grabado exitosamente", "Registro de estudiantes", JOptionPane.INFORMATION_MESSAGE);
                mostrarJTableEstudiantes();
                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(null, "El correo " + correo_ins + " ya existe", "Registro de estudiantes", JOptionPane.ERROR_MESSAGE);
                txtCorreo_ins.requestFocus();
            }            
        } else {
            JOptionPane.showMessageDialog(null, "Faltan datos por llenar", "Registro de estudiantes", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!txtCorreo_ins.getText().isEmpty() && !txtCorreo_per.getText().isEmpty() && !txtNum_cel.getText().isEmpty() && !txtNum_fijo.getText().isEmpty() && !txtPrograma.getText().isEmpty()){
            correo_ins = txtCorreo_ins.getText();
            if (e.verificarBD(correo_ins)) {
                correo_ins = txtCorreo_ins.getText();
                correo_per = txtCorreo_per.getText();
                num_cel = Long.parseLong(txtNum_cel.getText());
                num_fijo = Long.parseLong(txtNum_fijo.getText());
                programa = txtPrograma.getText();
                e.modificarEstudiante(correo_ins, correo_per, num_cel, num_fijo, programa);
                JOptionPane.showMessageDialog(null,"El registro fue actualizado exitosamente", "Registro de estudiantes", JOptionPane.INFORMATION_MESSAGE);
                mostrarJTableEstudiantes();
                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(null, "El correo " + correo_ins + " no existe", "Registro de estudiantes", JOptionPane.ERROR_MESSAGE);
                txtCorreo_ins.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Faltan datos por llenar", "Registro de estudiantes", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!txtCorreo_ins.getText().isEmpty()){
            correo_ins = txtCorreo_ins.getText();
            if (e.verificarBD(correo_ins)) {
                e.eliminarEstudiante(correo_ins);
                JOptionPane.showMessageDialog(null,"El registro fue eliminado exitosamente", "Registro de estudiantes", JOptionPane.INFORMATION_MESSAGE);
                mostrarJTableEstudiantes();                
                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(null, "El correo " + correo_ins + " no existe", "Registro de estudiantes", JOptionPane.ERROR_MESSAGE);
                txtCorreo_ins.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Faltan datos por llenar", "Registro de estudiantes", JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        limpiarDatos();        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int res = 0;
        res = JOptionPane.showConfirmDialog(null, "¿Desea salir del programa?", "Finalizar programa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
            c.cerrarConexion();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jTableEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstudiantesMouseClicked
        if(jTableEstudiantes.getSelectedRow() != -1){
            String correo_ins;
            correo_ins = (String) jTableEstudiantes.getValueAt(jTableEstudiantes.getSelectedRow(), 3);
            buscarEstudiantes(correo_ins);
        }
    }//GEN-LAST:event_jTableEstudiantesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableEstudiantes;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtCorreo_ins;
    public javax.swing.JTextField txtCorreo_per;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtNum_cel;
    public javax.swing.JTextField txtNum_fijo;
    public javax.swing.JTextField txtPrograma;
    // End of variables declaration//GEN-END:variables
}
